name: Directory
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List dirs
        run: |
          ls -a
          env
        working-directory: /tmp
        env:
            HMM_PROFILE_RUN_INTEGRITY_TESTS: 'TRUE'

